[MOGURI-4] add : accountBook CRUD 구현
Asthux/Moguri pull request #1
Opened 2024-09-20 08:52 UTC by owzl

<반영 및 수정>
accountbook 폴더 전체
resources > AccountBook.xml
RootConfig, ServletConfig 
mybatis-config.xml 별칭

<comment>
getAccountBookList 잘 되는 것 확인
SQL 오타 수정해야될 것들 있을 수 있음
추후 DB 수정할 수도 있음
- null 여부, 날짜 default값 등
- 카테고리 관련(gpt)
- 컬럼명 type

2024-09-22 08:59 UTC, Asthux requested changes
고치고 다시 push해서 알려주세요

2024-09-22 08:59 UTC, Asthux commented on moguri/src/main/java/org/moguri/accountbook/domain/AccountBookVO.java
Domain 네이밍은 VO를 안쓰는게 좋을 것 같습니다

2024-09-22 08:59 UTC, Asthux commented on moguri/src/main/java/org/moguri/accountbook/controller/AccountBookController.java
getAccountBookList 보다는 getAccountBooks 로 하는게 좋아보입니다.
update 부분에 set 메서드를 사용해서 값을 넣어주는게 아니라 service에 id, param 해서 두개를 보내는 것이 좋아보입니다.

2024-09-23 04:38 UTC, owzl commented on moguri/src/main/java/org/moguri/accountbook/domain/AccountBookVO.java
c3b6c2a 수정 완료

2024-09-23 05:28 UTC, owzl commented on moguri/src/main/java/org/moguri/accountbook/controller/AccountBookController.java
c3b6c2a
- getAccountBookList -> getAccountBooks
   => 수정 완료
- update 부분 set 메서드 사용 -> service에 id, param 보내는 방식으로 구현
   => 수정했는데 맞게 했는지 모르겠으니 확인 부탁드립니다.
- getAccountBook 캐스팅 관련 오류 해결 도움 요청
  : Request processing failed; nested exception is java.lang.ClassCastException: class org.moguri.accountbook.domain.AccountBook cannot be cast to class java.util.Optional (org.moguri.accountbook.domain.AccountBook is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @38ea768; java.util.Optional is in module java.base of loader 'bootstrap')

2024-09-25 00:14 UTC, merged