[MOGURI-6] add : goal CRUD 구현
Asthux/Moguri pull request #3
Opened 2024-09-22 06:01 UTC by runeunrun

1. goal CRUD 구현
2. rootconfig scan 경로 설정
3. application properties 수정

2024-09-22 09:07 UTC, Asthux requested changes

2024-09-22 09:07 UTC, Asthux commented on moguri/src/main/java/org/moguri/goal/controller/GoalController.java
네이밍 할 때 무엇을 get 해오는지 명확히 써오는게 좋습니다. getGoal로 수정하면 좋을 것 같습니다.
그리고 PathVariable 받아올 때 long으로 받아주세요.
update 때 set 메서드를 쓰지 않고 service에 id, param 두개를 넘겨주는 것이 좋습니다.

2024-09-22 09:07 UTC, Asthux commented on moguri/src/main/java/org/moguri/goal/service/GoalServiceImpl.java
exception은 customException을 구현해놨으니 그것을 사용해주세요

2024-09-23 06:39 UTC, runeunrun commented on moguri/src/main/java/org/moguri/goal/controller/GoalController.java
요청 반영 사항
1. getGoal로 수정 완료
2. int에서 long으로 타입 변환 완료
3. id와 param을 넘겨주는 구조로 변환 완료

2024-09-23 06:41 UTC, runeunrun commented on moguri/src/main/java/org/moguri/goal/service/GoalServiceImpl.java
요청 반영 사항
1. NosuchElementException을 MoguriLogicException으로 변경 완료

2024-09-24 01:36 UTC, closed without merging