[MORURI-2] add : event(attendance, quiz) CRUD 구현
Asthux/Moguri pull request #5
Opened 2024-09-23 01:05 UTC by ShinDong17

<반영 사항>

1. event 폴더 전체
2. event 폴더 안 attendance, quiz CRUD 기능 개발
3. RootConfig, ServletConfig 수정
4. mybatis-config.xml 수정
5. resources > event 폴더 안 AttendanceMapper.xml, QuizMapper.xml 추가

2024-09-23 01:51 UTC, Asthux requested changes

2024-09-23 01:51 UTC, Asthux commented on moguri/src/main/java/org/moguri/event/attendance/controller/AttendanceController.java
List 자료형 말고 MoguriPage를 이용하고 메서드명 getAttendances로 수정하는게 좋아보입니다.
AttendanceItem, CreateRequest에 snakeCase 말고 CamelCase로 변경해주세요.

2024-09-23 01:51 UTC, Asthux commented on moguri/src/main/java/org/moguri/event/attendance/domain/Attendance.java
여기도 CamelCase로 변경해주세요

2024-09-23 01:51 UTC, Asthux commented on moguri/src/main/java/org/moguri/event/attendance/param/AttendanceCreateParam.java
CamelCase

2024-09-23 01:51 UTC, Asthux commented on moguri/src/main/java/org/moguri/event/attendance/service/AttendanceServiceImpl.java
create부분에 try-catch문은 추후에 중복확인 메서드를 추가 후 getAttendance처럼 .orElseThrow를 사용하는 방법으로 변경할게요

2024-09-23 01:51 UTC, Asthux commented on moguri/src/main/resources/application.properties
주석부분 삭제해주세요

2024-09-24 07:12 UTC, ShinDong17 commented on moguri/src/main/java/org/moguri/event/attendance/controller/AttendanceController.java
수정 완료

2024-09-24 07:13 UTC, ShinDong17 commented on moguri/src/main/java/org/moguri/event/attendance/domain/Attendance.java
수정 완료

2024-09-24 07:13 UTC, ShinDong17 commented on moguri/src/main/java/org/moguri/event/attendance/param/AttendanceCreateParam.java
수정 완료

2024-09-24 07:13 UTC, ShinDong17 commented on moguri/src/main/java/org/moguri/event/attendance/service/AttendanceServiceImpl.java
확인 완료

2024-09-24 07:13 UTC, ShinDong17 commented on moguri/src/main/resources/application.properties
수정 완료

2024-09-25 00:52 UTC, merged