[Moguri-6] goal CRUD 구조 변경 및 git 충돌 해결
Asthux/Moguri pull request #8
Opened 2024-09-25 08:19 UTC by runeunrun

1. goal CRUD 구조 변경
- goalController : get -> getGoal로 변경, update 시 id와 param을 사용하여 구현
- goalService : customException으로 구현 완료
2. goal CRUD 충돌 해결

2024-09-25 08:32 UTC, Asthux requested changes

2024-09-25 08:32 UTC, Asthux commented on moguri/src/main/java/org/moguri/goal/repository/GoalMapper.java
interface의 모든 메서드는 default로 public이기 때문에 쓸 필요가 없습니다 삭제해주세요

2024-09-25 08:32 UTC, Asthux commented on moguri/src/main/java/org/moguri/goal/controller/GoalController.java
update랑 delete 구현이 안되어있는데요? 재확인 부탁드립니다

2024-09-25 08:32 UTC, Asthux commented on moguri/src/main/java/org/moguri/goal/service/GoalService.java
Service update, delete, create에서 Goal을 return하시는 이유가 있나요?

2024-09-26 10:06 UTC, runeunrun commented on moguri/src/main/java/org/moguri/goal/service/GoalService.java
update, delete, create 하고 나서 goal을 다시 조회하면 안될까요? return하지 않으려고 하니, 오류가 떠서 물어봅니다.

2024-09-26 10:06 UTC, runeunrun commented on moguri/src/main/java/org/moguri/goal/repository/GoalMapper.java
삭제 완료했습니다.

2024-09-30 02:13 UTC, merged